---
title: Promise自定义分装
date: 2022-04-26 16:07:55
permalink: /pages/899a0f/
tags:
  - 
author: 
  name: yami
  link: https://github.com/yamin-hub
categories: JS文章
---
# Promise自定义封装

## 1.初始结构搭建

```js
//promise基本使用
let p = new Promise((resolve,reject)=>{
    //this指向window
    resolve('ok')
})
p.then(value=>{
    console.log(value)
},reason=>{
   console.log(reason)
})
```



```js
function Promise(executor){
    executor()
}
Promise.prototype.then = function(onResolved,onRejected){
    
}
```

## 2.resolve和reject

```js
function Promise(executor){
    //resolve函数
    function resolve(){
        
    }
    //reject函数
    function reject(){
        
    }
    //resolve,reject同时存在，但只有一个真正执行
    executor(resolve,reject)
}
Promise.prototype.then = function(onResolved,onRejected){
    
}
```

## 3.改变状态和设置结果值

调用resolve的时候，promise状态改为fulfiled，并保存相应的值；调用reject的时候，promise状态改为rejected，并保存相应的值

```js
function Promise(executor){
    //添加属性
    this.PromiseState = 'pending';
    this.PromiseResult = null;
    
    //保存实例对象的this值
     /*   let p = new Promise((resolve,reject)=>{
            //resolve内部this指向window
            resolve('ok')
          }) */
    const self = this
    //resolve函数
    function resolve(data){
        if(self.PromiseState !== 'pending') return   
       //1. 修改对象的状态（promiseState）
        self.PromiseState = 'fulfiled';
       //2. 设置对象结果值（promiseResult）
        self.PromiseResult = data;
    }
    //reject函数
    function reject(data){
       //1. 修改对象的状态（promiseState）
        self.PromiseState = 'rejected';
       //2. 设置对象结果值（promiseResult）
        self.PromiseResult = data;
    }
    executor(resolve,reject)
}
Promise.prototype.then = function(onResolved,onRejected){
    
}
```

## 4.通过抛出异常改变promise状态

```js
let p = new Promise((resolve,reject)=>{
    //修改promise状态为reject,且结果为抛出的错误
    throw 'error'
})
```

判断是否抛出异常，抛出异常则修改为reject的结果

```js
//主要对executor部分进行修改

//修改前
executor(resolve,reject)

//修改后
try{
    executor(resolve,reject)
}catch(e){
    reject(e)
}
```

## 5.状态只能修改一次

```js
let p = new Promise((resolve,reject)=>{
    reject('error')
    resolve('ok')
})
```

多次调用reject和resolve的时候的情况，修改方法为在resolve和reject中判断是否为pending状态，如果为pending状态，则返回

```js
//在修改之前判断一下状态是否为pending
    function resolve(data){
        //promise状态只能修改一次
        if(self.PromiseState !== 'pending') return   
        self.PromiseState = 'fulfiled';
        self.PromiseResult = data;
    }
    //reject函数
    function reject(data){
        if(self.PromiseState !== 'pending') return   
        self.PromiseState = 'rejected';
        self.PromiseResult = data;
    }
```

## 6.then 方法执行回调

```js
//promise基本使用
let p = new Promise((resolve,reject)=>{
    //this指向window
    resolve('ok')
})
p.then(value=>{
    console.log(value)  //执行成功回调
},reason=>{
   console.log(reason)  //执行失败回调
})
```

主要在then函数中判断两种状态的回调。

```js
//主要修改then方法
Promise.prototype.then = function(onResolved,onRejected){
    //调用回调函数
    if(this.PromiseState === 'fulfilled'){
        onResolved(this.PromiseResult)
    }
    if(this.PromiseState === 'rejected'){
        onRejected(this.PromiseResult)
    }
}
```

## 7.异步任务 then方法实现

```js
let p = new Promise((resolve,reject) =>{
    setTimeout(()=>{
        resolve('ok')
    },1000)
});
p.then(value=>{
    console.log(value)  //执行成功回调
},reason=>{
   console.log(reason)  //执行失败回调
})
```

在then函数中添加pending状态的处理，同时保存相应的回调函数，在改变promise状态的时候再执行回调函数。

```js

function Promise(executor){
    //添加属性
    this.PromiseState = 'pending';
    this.PromiseResult = null;
    this.callback = {};

    const self = this;
    //resolve函数
    function resolve(data){
        if(self.PromiseState !== 'pending') return ;  
        self.PromiseState = 'fulfiled';
        self.PromiseResult = data;
        //调用成功的回调函数
        if(self.callback.onResolved){
            self.callback.onResolved(data)
        }
    }
    //reject函数
    function reject(data){
        if(self.PromiseState !== 'pending') return ;  
        self.PromiseState = 'rejected';
        self.PromiseResult = data;
        //调用失败的回调函数
        if(self.callback.onRejected){
            self.callback.onRejected(data)
        }
    }


//then函数
Promise.prototype.then = function(onResolved,onRejected){
    //调用回调函数
    if(this.PromiseState === 'fulfilled'){
        onResolved(this.PromiseResult)
    }
    if(this.PromiseState === 'rejected'){
        onRejected(this.PromiseResult)
    }
    //在异步的时候，如果是一个pending状态的时候
    if(this.PromiseState === 'pending'){
        //保存回调函数
        this.callback = {
           onResolved,
           onRejected
        }
    }
}
```

## 8.多个回调问题

```js
let p = new Promise((resolve,reject) =>{
    setTimeout(()=>{
        resolve('ok')
    },1000)
});
p.then(value=>{
    console.log(value)  //执行成功回调
},reason=>{
   console.log(reason)  //执行失败回调
})
p.then(value=>{
   alter(value)  //执行成功回调
},reason=>{
  alter(reason)  //执行失败回调
})
```

修改方法：将callback改成一个数组，多对成功，失败回调存放进入数组里面,最后修改resolve和reject的相应回调代码

```js
function Promise(executor){
    //添加属性
    this.PromiseState = 'pending';
    this.PromiseResult = null;
    this.callbacks = [];  //改变成一个数组，方面存放多个回调

    const self = this;
    //resolve函数
    function resolve(data){
        if(self.PromiseState !== 'pending') return ;  
        self.PromiseState = 'fulfiled';
        self.PromiseResult = data;
        //调用成功的回调函数
        self.callbacks.forEach(item =>{
            item.onResolved(data)
        })
    }
    //reject函数
    function reject(data){
        if(self.PromiseState !== 'pending') return ;  
        self.PromiseState = 'rejected';
        self.PromiseResult = data;
        //调用失败的回调函数
         self.callbacks.forEach(item =>{
            item.onRejected(data)
        })
    }


//then函数
Promise.prototype.then = function(onResolved,onRejected){
    //调用回调函数
    if(this.PromiseState === 'fulfilled'){
        onResolved(this.PromiseResult)
    }
    if(this.PromiseState === 'rejected'){
        onRejected(this.PromiseResult)
    }
    //在异步的时候，如果是一个pending状态的时候
    if(this.PromiseState === 'pending'){
        //保存回调函数
        this.callback.push({
           onResolved,
           onRejected
        })
    }
}
```

## 9.同步任务 then返回结果

```js
let p = new Promise((resolve,reject) =>{
        resolve('ok')
});
const result =  p.then(value=>{
    console.log(value)  //执行成功回调
},reason=>{
   console.log(reason)  //执行失败回调
})
console.log(result)

//结果
Promise {<pending>}
	[[Prototype]]:Promise
    [[PromiseState]]:'fulfilled'
    [[PromiseResult]]:undefined
ok
```

then结果为promise类型对象。具体表现为：

执行成功/失败回调情况下，且回调的返回值为非promise对象的时候，则then的结果为成功的promise对象，返回结果为promise的时候，then的返回值和回调返回的promise状态以及值相同。

```js
//then函数
Promise.prototype.then = function(onResolved,onRejected){
    const self = this
    return new Promise((resolve,reject)=>{
        //定义then的返回结果函数callback,注意该函数会直接在window环境下直接执行，所以里面的this指向window
        function callback(type){
          //try  catch是为了应对抛出异常错误
            try{
                let result =  type(self.PromiseResult);
                //返回是一个promise的情况
                if(result instanceof Promsie){
                    result.then(v=>{
                        resolve(v)
                    },r=>{
                        reject(r)
                    })
                }else {
                    resolve(result)
                }
            }catch(e){
                reject(e)
            }
        }
        //调用回调函数
        if(this.PromiseState === 'fulfilled'){
			callbak(onResolved)
        }
        if(this.PromiseState === 'rejected'){
           callback(onRejected)
        }
        //在异步的时候，如果是一个pending状态的时候
        if(this.PromiseState === 'pending'){
            //保存回调函数
            this.callbacks.push({
               onResolved,
               onRejected
            })
        } 
    })

```

## 10.异步任务 then返回结果

```js
let p = new Promise((resolve,reject)=>{
    setTimeout(()=>{
        resolve('ok')
    },1000)
})

//执行then方法
const res = p.then(value=>{
    console.log(value);
},reason =>{
    console.warn(reason)
})

console.log(res)

//结果
Promise {<pending>}
	[[Prototype]]:Promise
    [[PromiseState]]:'fulfilled'
    [[PromiseResult]]:undefined
undefined
ok
```

修改方法：异步执行的时候回调是一个pending状态，所以对then调用的时候走的是pending状态的判断，把回调存在callbacks这个变量里面，在异步执行resolve或reject的时候，再执行回调，和同步任务then返回结果一样处理，需要在callbacks的onResolved,onRejected的函数里面定义then返回结果处理的方法。

```js
//then函数
Promise.prototype.then = function(onResolved,onRejected){
    const self = this
    return new Promise((resolve,reject)=>{
        //定义then的返回结果函数
        function callback(type){
          //try  catch是为了应对抛出异常错误
            try{
                let result =  type(self.PromiseResult);
                if(result instanceof Promsie){
                    result.then(v=>{
                        resolve(v)
                    },r=>{
                        reject(r)
                    })
                }else {
                    resolve(result)
                }
            }catch(e){
                reject(e)
            }
        }
        //调用回调函数
        if(this.PromiseState === 'fulfilled'){
			callbak(onResolved)
        }
        if(this.PromiseState === 'rejected'){
           callback(onRejected)
        }
        //在异步的时候，如果是一个pending状态的时候
        if(this.PromiseState === 'pending'){
            //保存回调函数
            this.callbacks.push({
               onResolved:function(){
                  callback(onResolved)
               }
               onRejected:function(){
                  callback(onRejected)
               }
            })
        } 
    })
```

## 11.catch方法

```js
let p = new Promise((resolve,reject)=>{
    setTimeout(()=>{
        reject('ok')
    },1000)
})
p.catch(reason =>{
    console.warn(reason)
})
```

catch相当于then中只有失败回调的时候

```js
Promise.prototype.catch = function(onRejected){
   return this.then(undefined,onRejected)
}
```

## 12.异常穿透

```js
let p = new Promise((resolve,reject)=>{
    setTimeout(()=>{
        reject('ok')
    },1000)
})
p.then(value =>{
    console.log(111)
}).then(value =>{
    console.log(222)
}).then(value =>{
    console.log(333)
}).catch(reason =>{
    console.warn(reason)
})
```

当p是个异步promise任务的时候，在执行then的时候为pending状态，then只保存成功回调时，当出现错误调用错误回调的时候，会出现没有定义的情况，系统会报错。当然p如果是个成功的promise也会出现这种错误。修改这种错误，在then中添加一个判断，如果没有错误回调，但出错情况。

```js
 if(typeof onRejected !== 'function'){         
     onRejected = reason =>throw reason;                                                                    
 }                                             
```

当然成功回调没有，也是可以的。

```js
if(typeof onResolved !== 'function'){
    onResolved = value => value;
}
```

then方法的总代码

```js
//then函数
Promise.prototype.then = function(onResolved,onRejected){
    const self = this
    
     if(typeof onRejected !== 'function'){         
     	onRejected = reason =>throw reason;                                                                  
	 }  
     
    if(typeof onResolved !== 'function'){
    	onResolved = value => value;
	}
    
    return new Promise((resolve,reject)=>{
        //定义then的返回结果函数
        function callback(type){
          //try  catch是为了应对抛出异常错误
            try{
                let result =  type(self.PromiseResult);
                if(result instanceof Promsie){
                    result.then(v=>{
                        resolve(v)
                    },r=>{
                        reject(r)
                    })
                }else {
                    resolve(result)
                }
            }catch(e){
                reject(e)
            }
        }
        //调用回调函数
        if(this.PromiseState === 'fulfilled'){
			callbak(onResolved)
        }
        if(this.PromiseState === 'rejected'){
           callback(onRejected)
        }
        //在异步的时候，如果是一个pending状态的时候
        if(this.PromiseState === 'pending'){
            //保存回调函数
            this.callbacks.push({
               onResolved:function(){
                  callback(onResolved)
               }
               onRejected:function(){
                  callback(onRejected)
               }
            })
        } 
    })
```



## 13.Promise.resolve方法

```js
const p = Promise.resolved('ok')

//返回一个成功的promise
```

```js
Promise.resolve = function(value){
 //返回promise对象                                 
 return new Promise((resolve,reject) =>{       
     if(value instanceof Promise){             
         value.then(v =>{                      
             resolve(v)                        
         },r =>{                               
             reject(r)                         
         })                                    
     }else {                                   
         //状态设置为成功                             
         resolve(value);                       
     }                                         
 })                                            
}
```

## 14.Promise.reject方法

```js
const p = Promise.reject('error')
```

```js
Promise.reject = function(reason){
    return new Promise((resolve,reject)=>{
        reject(reason)
    })
}
```

## 15.Promise.all方法

```js
let p1 = new Promise((resolve,reject)=>{
    resolve('ok')
})
let p2 = Promise.resolve('Success')
let p3 = Promise,resolve('Oh Yeah')
let result = Promise.all([p1,p2,p3])
console.log(result)
```

特点：Promise.all(多个promise组成的数组)，如果都成功则，返回成功状态的promise,并且结果为各个promise结果都存入数组中

```js
Promise.all = function(promise){
    return new Promise((resolve,reject)=>{
        //声明计数变量和arr的数组
        let count = 0;
        let arr = [];
        //遍历
        for(let i = 0;i < promise.length; i++){
            promise[i].then(v=>{
                //对象状态成功，计数
                count++;
                //不能用push，用push顺序可能改变
                arr[i] = v;
                if(count === promise.length){
                    resolve(arr)
                }
            },r =>{
                reject(r)
            })
        }
    })
}
```

## 16.Promise.allSettled

allSettled方法与all方法不同，all只要有失败的promise直接返回失败状态的promise,结果的值为失败的值，而allSettled可以把所有的结果都用对象储存下来，保存在数组中。

```js
    let p1 = new Promise((resolve, reject) => {
        resolve('ok')
    })
    let p2 =Promise.reject('Error');
    let p3 = Promise.resolve('Oh Yeah');
    const result = Promise.allSettled([p1,p2,p3]);
    console.log(result)
// 最终输出： 
//    [
//      {status: "fulfilled", value: 'ok'},
//      {status: "fulfilled", value: 'Error'},
//      {status: "rejected", value: 'oh Yeah'},
//    ]
```

模拟allSettled方法

```js
 Promise.allSettled =function(promises){
        return new Promise((resolve,reject) =>{
            //声明变量
            let arr = [];
            let count  = 0
            //遍历
            for(let i = 0;i <promises.length;i++){
                promises[i].then(v =>{
                    arr[i] = {
                        status:'fulfilled',
                        value:v
                    }
                },r =>{
                   arr[i] ={
                       status:'rejected',
                       value:r
                   }
                })
            }
           resolve(arr)
        })
    }
```

## 17.Promise.race方法

```js
let p1 = new Promise((resolve,reject)=>{
    setTimeout(()=>{
        resolve('ok')
    })
})
let p2 = Promise.resolve('Success')
let p3 = Promise.resolve('oh yeah')

//调用race方法
let result = Promise.race([p1,p2,p3])  
```

特点：几个promise中谁最先改变状态，就返回谁的。

```js
Promise.race = function(promises){
    return new Promise((resolve,reject)=>{
        for(let i = 0;i < promises.length;i++){
            promises[i].then(v =>{
                //修改返回对象的状态为【成功】
                resolve(v)
            },r =>{
                //修改返回对象的状态为【失败】
                reject(r)
            })
        }
    })
}
```

## 18.回调是异步执行

promise中不论异步还是同步，回调都是异步执行的。

```js
let p1 = new Promise((resolve,reject) =>{
    resolve('ok')
    console.log(111)
})

p1.then(value =>{
    console.log(222)
})

console.log(333)

//结果
111  333  222
```

需要对promise中回调进行异步处理，改变的有then方法中的，异步回调中resolve，reject中的回调。

```js
function Promise(executor){
    //添加属性
    this.PromiseState = 'pending';
    this.PromiseResult = null;
    this.callback = {};

    const self = this;
    //resolve函数
    function resolve(data){
        if(self.PromiseState !== 'pending') return ;  
        self.PromiseState = 'fulfiled';
        self.PromiseResult = data;
        //调到成功的回调函数
        setTimeout(() =>{
            self.callbacks.forEach(item =>{
                item.onResolved(data);
            })
        })
    }
    //reject函数
    function reject(data){
        if(self.PromiseState !== 'pending') return ;  
        self.PromiseState = 'rejected';
        self.PromiseResult = data;
        //调用失败的回调函数
        setTimeout(() =>{
            self.callbacks.forEach(item =>{
                item.onRejected(data);
            })
        })
    }
```



```js
//then函数
Promise.prototype.then = function(onResolved,onRejected){
    const self = this
    
     if(typeof onRejected !== 'function'){         
     	onRejected = reason =>throw reason;                                                                  
	 }  
     
    if(typeof onResolved !== 'function'){
    	onResolved = value => value;
	}
    
    return new Promise((resolve,reject)=>{
        //定义then的返回结果函数
        function callback(type){
          //try  catch是为了应对抛出异常错误
            try{
                let result =  type(self.PromiseResult);
                if(result instanceof Promsie){
                    result.then(v=>{
                        resolve(v)
                    },r=>{
                        reject(r)
                    })
                }else {
                    resolve(result)
                }
            }catch(e){
                reject(e)
            }
        }
        //异步调用回调函数
        if(this.PromiseState === 'fulfilled'){
            setTimeout(() =>{
                callbak(onResolved)
            })
        }
        if(this.PromiseState === 'rejected'){
           setTimeout(() =>{
               callback(onRejected)
            })
        }
        //在异步的时候，如果是一个pending状态的时候
        if(this.PromiseState === 'pending'){
            //保存回调函数
            this.callbacks.push({
               onResolved:function(){
                  callback(onResolved)
               }
               onRejected:function(){
                  callback(onRejected)
               }
            })
        } 
    })
```

## 19.Class版本的整个Promise的自定义

```js
class Promise {
    //构造方法
    constructor(executor) {
        //添加属性
        this.PromiseState = 'pending';
        this.PromiseResult = null;
        //声明属性
        this.callbacks = [];
        const self = this
        //resolve函数
        function resolve(data){
            if(self.PromiseState !== 'pending') return
            //1.修改对象的状态(promiseState)
            self.PromiseState = 'fulfilled';
            //2.设置对象结果值(promiseResult)
            self.PromiseResult =data;
            //调到成功的回调函数
            setTimeout(() =>{
                self.callbacks.forEach(item =>{
                    item.onResolved(data);
                })
            })
        }
        //reject函数
        function reject(data){
            if(self.PromiseState !== 'pending') return
            //1.修改对象的状态(promiseState)
            self.PromiseState = 'rejected';
            //2.设置对象结果值(promiseResult)
            self.PromiseResult =data;
            //调用失败的回调函数
            setTimeout(() =>{
                self.callbacks.forEach(item =>{
                    item.onRejected(data);
                })
            })
        }
        try{
            //同步调用[执行器函数]
            executor(resolve,reject);
        }catch (e){
            //修改promise对象状态为[失败]
            reject(e);
        }
    }

    //then方法封装
    then(onResolved,onRejected){
        const self = this;
        //判断回调函数参数
        if(typeof onRejected !== 'function'){
            onRejected = reason =>{
                throw reason;
            }
        }
        if(typeof onResolved !== 'function') {
            onResolved = value => value;
        }
        return new Promise((resolve,reject) =>{
            //封装函数
            function callback(type){
                try{
                    let result = type(self.PromiseResult);
                    //判断
                    if(result instanceof Promise){
                        //如果是Promise类型的对象
                        result.then(v =>{
                            resolve(v)
                        },r =>{
                            reject(r)
                        })
                    }else {
                        //结果的对象为[成功]
                        resolve(result)
                    }
                }catch (e){
                    reject(e);
                }
            }
            //调用回调函数  PromiseState
            if(this.PromiseState === 'fulfilled'){
                setTimeout(() =>{
                    callback(onResolved);
                })
            }
            if(this.PromiseState === 'rejected'){
                setTimeout(() =>{
                    callback(onRejected);
                })
            }
            //判断pending状态
            if(this.PromiseState === 'pending'){
                //保存回调函数
                this.callbacks.push({
                    onResolved:function (){
                        callback(onResolved);
                    },
                    onRejected:function (){
                        callback(onRejected);
                    }
                })
            }
        })
    }

    //catch方法封装
    catch(onRejected){
        return this.then(undefined,onRejected)
    }

//resolve方法封装
    static resolve(value){
        //返回promise对象
        return new Promise((resolve,reject) =>{
            if(value instanceof Promise){
                value.then(v =>{
                    resolve(v)
                },r =>{
                    reject(r)
                })
            }else {
                //状态设置为成功
                resolve(value);
            }
        })
    }

    //reject方法封装
    static reject(value){
        return new Promise((resolve,reject) =>{
            reject(value);
        })
    }

    //all方法封装
    static all(promises){
        //返回结果为promise对象
        return new Promise((resolve,reject) =>{
            //声明变量
            let count = 0;
            let arr = [];
            //遍历
            for(let i =0; i<promises.length;i++ ){
                promises[i].then(v =>{
                    //得知对象的状态是成功
                    //每个promise对象都成功
                    count ++;
                    //将当前promise对象成功的结果 存入到数组中
                    arr[i] =v;
                    if(count === promises.length){
                        //修改状态
                        resolve(arr);
                    }
                },r =>{
                    //得知对象的状态是失败
                    reject(r);
                })
            }
        })
    }

    //allSettled方法
    static allSettled(promises){
        return new Promise((resolve,reject) =>{
            //声明变量
            let arr = [];
            let count  = 0
            //遍历
            for(let i = 0;i <promises.length;i++){
                promises[i].then(v =>{
                    arr[i] = {
                        status:'fulfilled',
                        value:v
                    }
                },r =>{
                   arr[i] ={
                       status:'rejected',
                       value:r
                   }
                })
            }
           resolve(arr)
        })
    }

    //race方法封装
    static race(promises){
        return new Promise((resolve,reject) =>{
            for(let i=0;i<promises.length;i++ ){
                promises[i].then(v =>{
                    //修改返回对象的状态为【成功】
                    resolve(v);
                },r=>{
                    //修改返回对象的状态为【失败】
                    reject(r);
                })
            }
        })
    }
}


```

## 20.aync关键字

在普通函数前面加上aync关键字的特点。

特点1：如果函数返回是一个非Promise类型的数据，则返回一个成功的Promise对象

特点2：如果函数返回是一个Promise类型的数据，则直接返回该成功或失败状态的promise

特点3：如果抛出异常，则返回的是一个失败的promise对象

## 21.await表达式

1. await 右侧的表达式一般为 promise 对象, 但也可以是其它的值
2. 如果表达式是 promise 对象, await 返回的是 promise 成功的值

3. 如果表达式是其它值, 直接将此值作为 await 的返回值

### 注意：

1. await必须写在async函数中，但async函数中可以没有await

2. 如果 await 的 promise 失败了, 就会抛出异常, 需要通过 try...catch 捕获处理

```js
//1.右侧为promise的情况
async function main(){
    let p = new Promise((resolve, reject) => {
        resolve('ok')
    })
    let res = await p;
    console.log(p)
}
main();  //  'ok'

//2.右侧为其他类型的情况
async function main(){
    let p = new Promise((resolve, reject) => {
        resolve('ok')
    })
    let res = await 20;
    console.log(p)
}
main();  //  20

//3.如果promise是失败的状态
async function main(){
    let p = new Promise((resolve, reject) => {
        reject('Error')
    })
    try{
        let res = await p;
    }catch(e){
        console.log(e)
    }
}
main();  //  'Error'
```

## 22.async与await结合

```js
const fs = require('fs');
const util = require('util');
//把传统函数改造成一个promise包裹的函数
const mineReadFile = util.promisify(fs.readFile);

//async与await
async function main(){
   try{
       //读取第一个文件的内容
       let data1 = await mineReadFile('./resource/1.html');
       let data2 = await mineReadFile('./resource/2.html');
       let data3 = await mineReadFile('./resource/3.html');
       console.log(data1 + data2 + data3);
   } catch (e){
       console.log(e)
   }
}
main()
```

## 23.promisify

```js

function promisify(original, manyArgs = false) {
    return function () {
        return new Promise((resolve, reject) => {
            original(...arguments, (err, ...values) => {
                if (err) return reject(err);
                return resolve(manyArgs ? values : values[0]);
            });
        });
    };
}

//fs.readFile是通过回调来获取数据的。正好对应(err,...values)=>{ ... }
let readFile = promisify(require('fs').readFile)
console.log(readFile('./resource/content.txt','utf-8')
    .then(data=>console.log(data)))
```

## 24.promise局限性

### 1. 错误被吃掉

首先我们要理解，什么是错误被吃掉，是指错误信息不被打印吗？

并不是，举个例子：

```js
throw new Error('error');
console.log(233333);
```

在这种情况下，因为 throw error 的缘故，代码被阻断执行，并不会打印 233333，再举个例子：

```js
const promise = new Promise(null);
console.log(233333);
```

以上代码依然会被阻断执行，这是因为如果通过无效的方式使用 Promise，并且出现了一个错误阻碍了正常 Promise 的构造，结果会得到一个立刻跑出的异常，而不是一个被拒绝的 Promise。

然而再举个例子：

```js
let promise = new Promise(() => {
    throw new Error('error')
});
console.log(2333333);
```

这次会正常的打印 `233333`，说明 Promise 内部的错误不会影响到 Promise 外部的代码，而这种情况我们就通常称为 “吃掉错误”。

其实这并不是 Promise 独有的局限性，try..catch 也是这样，同样会捕获一个异常并简单的吃掉错误。

而正是因为错误被吃掉，Promise 链中的错误很容易被忽略掉，这也是为什么会一般推荐在 Promise 链的最后添加一个 catch 函数，因为对于一个没有错误处理函数的 Promise 链，任何错误都会在链中被传播下去，直到你注册了错误处理函数。

### 2. 单一值

Promise 只能有一个完成值或一个拒绝原因，然而在真实使用的时候，往往需要传递多个值，一般做法都是构造一个对象或数组，然后再传递，then 中获得这个值后，又会进行取值赋值的操作，每次封装和解封都无疑让代码变得笨重。

说真的，并没有什么好的方法，建议是使用 ES6 的解构赋值：

```js
Promise.all([Promise.resolve(1), Promise.resolve(2)])
.then(([x, y]) => {
    console.log(x, y);
});
```

### 3. 无法取消

Promise 一旦新建它就会立即执行，无法中途取消。

### 4. 无法得知 pending 状态

当处于 pending 状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。
